chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('room/<int:course_id>/', views.course_chat_room, name='course_chat_room'),
]

educa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from courses.views import CourseListView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('course/', include('courses.urls')),
    path('service/', include('service.urls')),
    path('', CourseListView.as_view(), name='course_list'),
    path('students/', include('students.urls')),
    path('api/', include('courses.api.urls', namespace='api')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('home/', include('home.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name='payment'

urlpatterns=[
    path('', views.rate_list, name='rate'),
    ]

payment/models.py
from django.db import models

class Rate(models.Model):
	nome=models.CharField(max_length=200)
	contacto=models.CharField(max_length=30, blank=True)
	morada=models.CharField(max_length=200)
	email=models.EmailField()
	comprovativo=models.FileField(upload_to='uploads/', blank=True)

	def __str__(self):
		return self.nome


# Create your models here.

payment/forms.py
from django import forms
from .models import Rate

class RateForm(forms.ModelForm):
	class Meta:
		model=Rate
		fields=['nome', 'contacto', 'morada', 'email','comprovativo']
		labels={'nome':'Nome'}

payment/views.py
from django.shortcuts import render, redirect

from .models import Rate
from .forms import RateForm

def rate_list(request):
	if request.method != 'POST':
		form=RateForm()
	else:
		form=RateForm(data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('http://127.0.0.1:8000/home/')
	context={'form':form}
	return render(request, 'payment/rate.html', context)
			

# Create your views here.

payment/templates/payment/rate.html
 {% extends "base.html"%}
 {% block content%}
<html>
<title>Formulário de tarifa</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="w3-white w3-margin">
	
    <form action="{% url 'payment:rate' %}" class="w3-container" enctype= "multipart/form-data" method='post'>

    <h1>Formulário de tarifa</h1> 

    <br><label for="fnome">Nome</label>
    <input class="w3-input" id="fnome" name="fnome" type="text">	

    <br><label for="fcontacto">Contacto</label>
    <input class="w3-input" id="fcontacto" name="fcontacto" type="number">

    <br><label for="fmorada">Morada</label>
    <input class="w3-input" id="fmorada" name="fmorada" type="text">

    <br><label for="femail">Email</label>
    <input class="w3-input" id="femail" name="femail" type="Email">

    <br><label for="fcomprovativo">Comprovativo</label>
    <input class="w3-input" id="fcomprovativo" name="fcomprovativo" type="file">

    <input type="submit" value="ENVIAR FORMULÁRIO">
    {% csrf_token %}
    
     	
    </form>

    <div class="w3-white w3-margin" style="font-family: 'Trebuchet MS', sans-serif;">
     
     
 <p><strong>OBS:</strong>Por favor enviar o comprovativo através do contacto disponível ou anexar o mesmo, após a confirmação do pagamento receberá um link por email dentro de 24h, para que então continue com o processo de cadastramento e tenha acesso aos conteúdos.</p>
 </p>
     

</div> 



</body>
</html>

 

 {% endblock %}